# Generated by Django 5.1.1 on 2024-10-25 17:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_img",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Makale Fotoğrafı"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="İçerik"),
        ),
    ]
