# Generated by Django 5.1.1 on 2024-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_article_article_img_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Onaylı mı?"),
        ),
    ]
