# Generated by Django 5.1.1 on 2024-11-08 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_footersettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footersettings",
            old_name="addres",
            new_name="address",
        ),
    ]
