# Generated by Django 5.1.2 on 2024-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_rename_addres_footersettings_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name=" Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "service_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="service_manager",
                        verbose_name="Resım",
                    ),
                ),
            ],
        ),
    ]
